name: terrafrom-deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform_checkout_and_azlogin: 
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.1

      - name: Azure login
        uses: Azure/login@v2.3.0
        with: 
          creds: ${{secrets.INFRACODE}}

  terraform_install:
    runs-on: self-hosted

    steps:
      - name: terraform install
        uses: hashicorp/setup-terraform@v2.0.3

      - name: teraform version check
        run: terraform -version

      - name: path set
        run: |
          echo "$HOME/.terraform-bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name : terraform init
        run  : terraform init
    
      - name : terraform plan
        run  : terraform plan

    
      
        
        
